version: "3.3"
services:
   jenkins:
      image:  4oh4/jenkins-docker
      ports:
        - "8080:8080"
        - "50000:50000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /home/merlinoff/Downloads/jenkins_home:/var/jenkins_home